# Zebra configuration file for devnet
[network]
listen_addr = "0.0.0.0"
network = "Regtest"

[consensus]
checkpoint_sync = false

[mempool]
tx_cost_limit = 80000000
eviction_memory_time = "1h"

[state]
cache_dir = "/zebrad-cache"
ephemeral = false

[sync]
download_concurrency_limit = 50
lookahead_limit = 2000

[tracing]
use_color = true
format = "full"

[metrics]
endpoint_addr = "0.0.0.0:9999"

[rpc]
listen_addr = "0.0.0.0:18232"